/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AllStudentsFram.java
 *
 * Created on Jan 9, 2014, 12:14:33 PM
 */

package guiapp;

import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author Sk8withaguitar
 */
public class AllStudentsFram extends javax.swing.JFrame {
private javax.swing.JButton jButtonArrays[];
//private JPanel jp = new JPanel();

    /** Creates new form AllStudentsFram */
    public AllStudentsFram() {
        initComponents();
    }
    
    void setButtonSize (int size)
    { 
    jButtonArrays = new javax.swing.JButton[size]; 
    }
    
    void createButtonArray()
    {
    int i = 0;
    for (JButton jButtonArray : jButtonArrays)
    {
    jButtonArrays[i] = new JButton();
    jButtonArrays[i].setText("Button " + i);
    //jPanel1.add(jButtonArrays[i]);
    }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllStudentsFram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
